### ISSUE TITLE
Training Error on png(4 channel input) images

### ISSUE THREAD

**Issue by ashishkr23** [NVIDIA/pix2pixHD#119]
Hi Guys,

I am trying to train a network on a data set that has four channels I/O image pairs.
python train.py --name tshirts --label_nc 0 --no_instance --tf_log  --dataroot datasets/tshirts/ --input_nc 4 --output_nc 4

I am running into the following error. Would be great if anyone could give me some pointers.Similar process runs fine for 3 channel I/O pairs
----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/projects/python/clip-gan-rf/models/pix2pixHD_model.py", line 165, in forward
    fake_image = self.netG.forward(input_concat)
  File "/home/ubuntu/projects/python/clip-gan-rf/models/networks.py", line 176, in forward
    output_prev = self.model(input_downsampled[-1])        
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 4, 7, 7], expected input[1, 3, 663, 518] to have 4 channels, but got 3 channels instead

**Comment by ashishkr23** [comment]
Update :
I was able to run it for png images, had to do following changes.

1. data/aligned_dataset.py line 65/44
convert('RGBA')

**Comment by yxt132** [comment]
I made it to run by modifying the code as ashishkr23 said. However, the intermediate results were shown as gray scale images. It seems the author made it black and white for visualization if the number of channels is greater than 3. Need some fix here.
