### ISSUE TITLE
Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'

### ISSUE THREAD

**Issue by kunalgoyal9** [NVIDIA/pix2pixHD#150]
I ran ./scripts/test_1024p.sh and got 

`Traceback (most recent call last):
  File "test.py", line 59, in <module>
    generated = model.inference(data['label'], data['inst'], data['image'])
  File "/home/ubuntu/atlas/pix2pixHD/models/pix2pixHD_model.py", line 198, in inference
    input_label, inst_map, real_image, _ = self.encode_input(Variable(label), Variable(inst), image, infer=True)
  File "/home/ubuntu/atlas/pix2pixHD/models/pix2pixHD_model.py", line 126, in encode_input
    edge_map = self.get_edges(inst_map)
  File "/home/ubuntu/atlas/pix2pixHD/models/pix2pixHD_model.py", line 264, in get_edges
    edge[:,:,:,1:] = edge[:,:,:,1:] | (t[:,:,:,1:] != t[:,:,:,:-1])
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'
`

Please help me resolve this

**Comment by Enuvesta** [comment]
Actually, changing version of torch to 1.0.1 works for me.

**Comment by ryangrahamnc** [comment]
What torchvision version is compatible with that? Is there a requirements.txt anywhere for this repo?

**Comment by ryangrahamnc** [comment]
Got it working with `conda install pytorch=1.0.1 torchvision=0.2.2 cudatoolkit=10 -c pytorch`

**Comment by uyekt** [comment]
Same problem here. (Using conda and python 3.7) 
Neither Pytorch 1.2, 1.3 nor 1.0.1 worked. Any clue why this happens?

**Comment by huangshenneng** [comment]
you can add 'edge=edge.bool()'     before 'edge[:,:,:,1:] = edge[:,:,:,1:] | (t[:,:,:,1:] != t[:,:,:,:-1]) '

**Comment by shikhar-scs** [comment]
@huangshenneng saviour 🙏

**Comment by craftsliu** [comment]
> you can add 'edge=edge.bool()' before 'edge[:,:,:,1:] = edge[:,:,:,1:] | (t[:,:,:,1:] != t[:,:,:,:-1]) '

good job.
