### ISSUE TITLE
Loading weights file and prediction

### ISSUE THREAD

**Issue by cfrancesco** [NVIDIA/pix2pixHD#159]
Hi,
first of all thank you for the great resource, I obtain really good results with very little effort and without pytorch knowledge.
However, after training the model, I cannot get around to generate predictions.
I used the default options for training:
```
python train.py --name own_data --dataroot datasets/own_data/ --no_flip --no_instance --label_nc 0 --tf_log
```

But now I am unable to recreate the model and cannot find the relative documentation.

Using this
```
import torch
from options.test_options import TestOptions
from models.models import create_model


opt = TestOptions().parse(save=False)
opt.nThreads = 1
opt.batchSize = 1
opt.serial_batches = True
opt.no_flip = True
model = create_model(opt)
```
return a Warning saying 
``` Pretrained network G has fewer layers; ```

while doing
``` model.load_state_dict(torch.load(FILE_PATH)) ```
throws an error regarding missing keys (I'm assuming due to layer mismatch)
```
 lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for InferenceModel:
	Missing key(s) in state_dict: "netG.model.1.weight", "netG.model.1.bias", "netG.model.4.weight", "netG.model.4.bias", "netG.model.7.weight", "netG.model.7.bias", "netG.model.10.weight", "netG.model.10.bias", "netG.model.13.weight", "netG.model.13.bias", "netG.model.16.conv_block.1.weight", "netG.model.16.conv_block.1.bias", "netG.model.16.conv_block.5.weight", "netG.model.16.conv_block.5.bias", "netG.model.17.conv_block.1.weight", "netG.model.17.conv_block.1.bias", "netG.model.17.conv_block.5.weight", "netG.model.17.conv_block.5.bias", "netG.model.18.conv_block.1.weight", "netG.model.18.conv_block.1.bias", "netG.model.18.conv_block.5.weight", "netG.model.18.conv_block.5.bias", "netG.model.19.conv_block.1.weight", "netG.model.19.conv_block.1.bias", "netG.model.19.conv_block.5.weight", "netG.model.19.conv_block.5.bias", "netG.model.20.conv_block.1.weight", "netG.model.20.conv_block.1.bias", "netG.model.20.conv_block.5.weight", "netG.model.20.conv_block.5.bias", "netG.model.21.conv_block.1.weight", "netG.model.21.conv_block.1.bias", "netG.model.21.conv_block.5.weight", "netG.model.21.conv_block.5.bias", "netG.model.22.conv_block.1.weight", "netG.model.22.conv_block.1.bias", "netG.model.22.conv_block.5.weight", "netG.model.22.conv_block.5.bias", "netG.model.23.conv_block.1.weight", "netG.model.23.conv_block.1.bias", "netG.model.23.conv_block.5.weight", "netG.model.23.conv_block.5.bias", "netG.model.24.conv_block.1.weight", "netG.model.24.conv_block.1.bias", "netG.model.24.conv_block.5.weight", "netG.model.24.conv_block.5.bias", "netG.model.25.weight", "netG.model.25.bias", "netG.model.28.weight", "netG.model.28.bias", "netG.model.31.weight", "netG.model.31.bias", "netG.model.34.weight", "netG.model.34.bias", "netG.model.38.weight", "netG.model.38.bias".
	Unexpected key(s) in state_dict: "model.1.weight", "model.1.bias", "model.4.weight", "model.4.bias", "model.7.weight", "model.7.bias", "model.10.weight", "model.10.bias", "model.13.weight", "model.13.bias", "model.16.conv_block.1.weight", "model.16.conv_block.1.bias", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.17.conv_block.1.weight", "model.17.conv_block.1.bias", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.18.conv_block.1.weight", "model.18.conv_block.1.bias", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.19.conv_block.1.weight", "model.19.conv_block.1.bias", "model.19.conv_block.5.weight", "model.19.conv_block.5.bias", "model.20.conv_block.1.weight", "model.20.conv_block.1.bias", "model.20.conv_block.5.weight", "model.20.conv_block.5.bias", "model.21.conv_block.1.weight", "model.21.conv_block.1.bias", "model.21.conv_block.5.weight", "model.21.conv_block.5.bias", "model.22.conv_block.1.weight", "model.22.conv_block.1.bias", "model.22.conv_block.5.weight", "model.22.conv_block.5.bias", "model.23.conv_block.1.weight", "model.23.conv_block.1.bias", "model.23.conv_block.5.weight", "model.23.conv_block.5.bias", "model.24.conv_block.1.weight", "model.24.conv_block.1.bias", "model.24.conv_block.5.weight", "model.24.conv_block.5.bias", "model.25.weight", "model.25.bias", "model.28.weight", "model.28.bias", "model.31.weight", "model.31.bias", "model.34.weight", "model.34.bias", "model.38.weight", "model.38.bias".
```

What's the preferred way of performing inference given the state dictionary?

Thank you

**Comment by cfrancesco** [comment]
This is the output log
```
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: []
how_many: 50
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 35
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
nThreads: 2
n_blocks_global: 9
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 4
n_local_enhancers: 1
name: label2city
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
norm: instance
ntest: inf
onnx: None
output_nc: 3
phase: test
resize_or_crop: scale_width
results_dir: ./results/
serial_batches: False
tf_log: False
use_dropout: False
use_encoded_image: False
verbose: False
which_epoch: latest
-------------- End ----------------
GlobalGenerator(
  (model): Sequential(
    (0): ReflectionPad2d((3, 3, 3, 3))
    (1): Conv2d(36, 64, kernel_size=(7, 7), stride=(1, 1))
    (2): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (3): ReLU(inplace=True)
    (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (5): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (8): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (11): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (12): ReLU(inplace=True)
    (13): Conv2d(512, 1024, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (14): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (15): ReLU(inplace=True)
    (16): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (17): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (18): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (19): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (20): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (21): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (22): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (23): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (24): ResnetBlock(
      (conv_block): Sequential(
        (0): ReflectionPad2d((1, 1, 1, 1))
        (1): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (2): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (3): ReLU(inplace=True)
        (4): ReflectionPad2d((1, 1, 1, 1))
        (5): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1))
        (6): InstanceNorm2d(1024, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
    )
    (25): ConvTranspose2d(1024, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (26): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (27): ReLU(inplace=True)
    (28): ConvTranspose2d(512, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (29): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (30): ReLU(inplace=True)
    (31): ConvTranspose2d(256, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (32): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (33): ReLU(inplace=True)
    (34): ConvTranspose2d(128, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), output_padding=(1, 1))
    (35): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
    (36): ReLU(inplace=True)
    (37): ReflectionPad2d((3, 3, 3, 3))
    (38): Conv2d(64, 3, kernel_size=(7, 7), stride=(1, 1))
    (39): Tanh()
  )
)
Pretrained network G has fewer layers; The following are not initialized:
['model']
```

**Comment by cfrancesco** [comment]
I was able to create the model, still not sure if this is the intended way. However when trying to predict, it will try to use CUDA, although, which is not enabled in my machine (as opposed to the training server). So I am still unable to get predictions.
(here I manually insert the arguments for clarity, is there a preferred way of avoid cl args?)
```
sys.argv.extend('--gpu_ids -1 --label_nc 0 --no_instance'.split())
opt = TestOptions().parse(save=False)
opt.nThreads = 1   # test code only supports nThreads = 1
opt.batchSize = 1  # test code only supports batchSize = 1
opt.serial_batches = True  # no shuffle
opt.no_flip = True  # no flip

model = create_model(opt)
import numpy as np
img = np.random.rand(1, 40,40,3)
t = torch.from_numpy(img)
model.inference(t, None, None)
```
Throws
```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-cadce9932daa>", line 1, in <module>
    model.inference(t, None, None)
  File ".../pix2pixHD/models/pix2pixHD_model.py", line 198, in inference
    input_label, inst_map, real_image, _ = self.encode_input(Variable(label), Variable(inst), image, infer=True)
  File ".../pix2pixHD/models/pix2pixHD_model.py", line 113, in encode_input
    input_label = label_map.data.cuda()
  File ".../lib/python3.7/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File ".../lib/python3.7/site-packages/torch/cuda/__init__.py", line 95, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by cfrancesco** [comment]
For anyone facing similar issues or having a similar question, here's a quick and dirty working solution.

```
import sys
import torch
import numpy as np
from PIL import Image
from options.test_options import TestOptions
from models.models import create_model
from torch.autograd.variable import Variable
import torchvision.transforms as transforms

def im2tensor(img_pil):
    """Go from a PIL image (0..255 RGB) to a (-1..1) tensor"""
    transform_list = [
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))
    ]
    transform = transforms.Compose(transform_list)
    t = transform(img_pil)
    return t.reshape((1, t.shape[0], t.shape[1], t.shape[2]))
    
    
sys.argv.extend('--gpu_ids -1 --label_nc 0 --no_instance'.split())
opt = TestOptions().parse(save=False)
opt.nThreads = 1   # test code only supports nThreads = 1
opt.batchSize = 1  # test code only supports batchSize = 1
opt.serial_batches = True  # no shuffle
opt.no_flip = True  # no flip

model = create_model(opt)

img = Image.open('2.png').resize((1024, 1024), Image.BICUBIC)
t = im2tensor(img)
inp = Variable(t, volatile=True)

result = model.netG.forward(inp)

img_out = result.detach().numpy()[0]
img_out = np.rollaxis(img_out, 0, 3)
img_out += 1
img_out /= 2
img_out *= 255
img_out = np.clip(img_out, 0, 255)
img_out = img_out.astype(np.uint8)
Image.fromarray(img_out).show()
```

**Comment by erinbeesley** [comment]
still getting this error, i'm not sure how i'm supposed to implement this solution above, but here is my code- i am inserting a StyleGAN2 tensor into a Pix2PixHD model.

`import sys
sys.path.insert(1, "../pix2pixHD")
from options.test_options import TestOptions
from models.models import create_model
from torch.autograd.variable import Variable
import torchvision.transforms as transforms

import argparse

import torch
from torchvision import utils
from model import Generator
from tqdm import tqdm

opt = TestOptions().parse(save=False)
opt.nThreads = 1   # test code only supports nThreads = 1
opt.batchSize = 1  # test code only supports batchSize = 1
opt.serial_batches = True  # no shuffle
opt.no_flip = True  # no flip

def generate(args, g_ema, device, mean_latent):

    with torch.no_grad():
        g_ema.eval()
        sample_z = torch.randn(args.sample, args.latent, device=device)

        sample, _ = g_ema(
            [sample_z], truncation=args.truncation, truncation_latent=mean_latent
        )
        
        model = create_model(opt)
        model.load_state_dict(torch.load("latest_net_G.pth"))
        sample = model.netG.forward(sample)
        utils.save_image(
            sample,
            "./sample/result1.png",
            nrow=1,
            normalize=True,
            range=(-1, 1),
        )
        print("saved image. congrats.")

if __name__ == "__main__":
    device = "cuda"

    parser = argparse.ArgumentParser(description="Generate samples from the generator")

    parser.add_argument(
        "--size", type=int, default=1024, help="output image size of the generator"
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=1,
        help="number of samples to be generated for each image",
    )
    parser.add_argument(
        "--pics", type=int, default=1, help="number of images to be generated"
    )
    parser.add_argument("--truncation", type=float, default=1, help="truncation ratio")
    parser.add_argument(
        "--truncation_mean",
        type=int,
        default=4096,
        help="number of vectors to calculate mean for the truncation",
    )
    parser.add_argument(
        "--ckpt",
        type=str,
        default="ffhq.pt",
        help="path to the model checkpoint",
    )
    parser.add_argument(
        "--channel_multiplier",
        type=int,
        default=2,
        help="channel multiplier of the generator. config-f = 2, else = 1",
    )

    args = parser.parse_args()

    args.latent = 512
    args.n_mlp = 8

    g_ema = Generator(
        args.size, args.latent, args.n_mlp, channel_multiplier=args.channel_multiplier
    ).to(device)
    checkpoint = torch.load(args.ckpt)

    g_ema.load_state_dict(checkpoint["g_ema"])

    if args.truncation < 1:
        with torch.no_grad():
            mean_latent = g_ema.mean_latent(args.truncation_mean)
    else:
        mean_latent = None

    generate(args, g_ema, device, mean_latent)`

**Comment by erinbeesley** [comment]
still getting this error, not sure how i'm supposed to implement the solution above since my code is pretty similar but i am inserting a tensor generated with the StyleGAN2 ffhq model into the Pix2PixHD model and getting the error mentioned in the issue. here is my code: 

`import sys
sys.path.insert(1, "../pix2pixHD")
from options.test_options import TestOptions
from models.models import create_model
from torch.autograd.variable import Variable
import torchvision.transforms as transforms

import argparse

import torch
from torchvision import utils
from model import Generator
from tqdm import tqdm

opt = TestOptions().parse(save=False)
opt.nThreads = 1   # test code only supports nThreads = 1
opt.batchSize = 1  # test code only supports batchSize = 1
opt.serial_batches = True  # no shuffle
opt.no_flip = True  # no flip

def generate(args, g_ema, device, mean_latent):

    with torch.no_grad():
        g_ema.eval()
        sample_z = torch.randn(args.sample, args.latent, device=device)

        sample, _ = g_ema(
            [sample_z], truncation=args.truncation, truncation_latent=mean_latent
        )
        
        model = create_model(opt)
        model.load_state_dict(torch.load("latest_net_G.pth"))
        sample = model.netG.forward(sample)
        utils.save_image(
            sample,
            "./sample/result1.png",
            nrow=1,
            normalize=True,
            range=(-1, 1),
        )
        print("saved image. congrats.")
`
