### ISSUE TITLE
train error with apex

### ISSUE THREAD

**Issue by TryingZ** [NVIDIA/pix2pixHD#182]
after  adding apex：python train.py --name xxx --label_nc 0 --no_instance --resize_or_crop none --fp16，it can not work. It works well without apex, just do : python train.py --name xxx --label_nc 0 --no_instance --resize_or_crop none
do you konw how to solve this problem? Thank you

Error iformation:
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    with amp.scale_loss(loss_G, optimizer_G) as scaled_loss: scaled_loss.backward()                
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: _cublasOpFromChar input should be 't', 'n' or 'c' but got `

**Comment by tripzero** [comment]
I did not see this when trying fp16.  Instead I saw https://github.com/NVIDIA/apex/issues/319 which trying the solution there, I get a 100% GPU forever with no training.

torch 1.4
