### ISSUE TITLE
'Pix2PixHDModel' object has no attribute 'module'

### ISSUE THREAD

**Issue by yejg2017** [NVIDIA/pix2pixHD#20]
When I run my own image data,I met this bug,and how  can I solved this problem?    
type(self).__name__, name))
AttributeError: 'Pix2PixHDModel' object has no attribute 'module'

**Comment by tcwang0509** [comment]
Which line in which file does this occur?

**Comment by alwynmathew** [comment]
I couldn’t find a `module` in `model`. Could you point me to the code section where its defined.
`AttributeError: 'model' object has no attribute 'module'`

**Comment by kondela** [comment]
I think it's related to the PyTorch version. AFAIK this repo was initially developed for PyTorch 0.5 or so.

 Currently, I am using PyTorch 1.6 and few minor modifications had to be made to make it work, one of which was refactoring `model.module. `to `model.`

**Comment by oatmeal3000** [comment]
When I use cpu only without GPU

create web directory ./checkpoints/melody/web...
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    optimizer_G, optimizer_D = model.module.optimizer_G, model.module.optimizer_D
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Pix2PixHDModel' object has no attribute 'module'

**Comment by joel1895** [comment]
I am also facing the error, any solution for this?

**Comment by kondela** [comment]
Any chance you are trying to run it using PyTorch >= 1.0 and on cpu? Try PyTorch 1.5/1.6 and a GPU

**Comment by AyeshaShafique** [comment]
i also need solution @joel1895

**Comment by alwynmathew** [comment]
Set `gpu_ids` as `-1` to run in `cpu`.

https://github.com/NVIDIA/pix2pixHD/blob/5a2c87201c5957e2bf51d79b8acddb9cc1920b26/models/models.py#L17

if `gpu_ids` is not set to `-1`, `model` will be wrapped in `DataParallel`

https://github.com/NVIDIA/pix2pixHD/blob/5a2c87201c5957e2bf51d79b8acddb9cc1920b26/models/models.py#L18

when its wrapped in `DataParallel`, everything in `model` can be only access like `model.module.something`

Hope this helped.

**Comment by kex243** [comment]
You can remove all instances of ".module" in train.py if commenting in  models.py `if opt.isTrain and len(opt.gpu_ids) and not opt.fp16:  model = torch.nn.DataParallel(model, device_ids=opt.gpu_ids) `
