### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 3984) exited unexpectedly

### ISSUE THREAD

**Issue by NavpreetDevpuri** [NVIDIA/pix2pixHD#203]
similar to https://github.com/NVIDIA/pix2pixHD/issues/197, https://github.com/NVIDIA/pix2pixHD/issues/58
I installed pytorch `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`
I installed python libraries dominate `pip install dominate`

When i tried `python test.py --name label2city_1024p --netG local --ngf 32 --resize_or_crop none`. It shows following error 

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Devpuri\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Devpuri\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Devpuri\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\AI\didoc scanner\pix2pixHD-master\test.py", line 38, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Devpuri\anaconda3\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 38, in <module>
    for i, data in enumerate(dataset):
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\Devpuri\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 3984) exited unexpectedly
```

**Comment by jis478** [comment]
I've experienced the same issue and I've resolved it by increasing shared memory when starting a docker container.

**Comment by Rembie01** [comment]
Thanks @NavpreetDevpuri, your fix worked wonders!
