### ISSUE TITLE
THCTensorScatterGather.cu line=380 error=59 : device-side assert triggered when using labels and nyuv2 dataset

### ISSUE THREAD

**Issue by entrpn** [NVIDIA/pix2pixHD#206]
Hello,

I trained a model using rgb values and the train folders train_A and train_B without any issues.

Now I wanted to use the nyuv2 dataset using the labels as input and rgb as outputs. 

I extracted the label images with the class labels in each pixel for a total of 985 classes including 0 as a no class.

I set up the images under `datasets/nyuv2/train_img/0.png` and `datasets/nyuv2/train_label/0.png`

However, I'm stuck trying to train as I keep getting an error when trying to one hot word encode. I run the following command:

`CUDA_LAUNCH_BLOCKING=1 python train.py --label_nc 895 --name nyuv2 --dataroot ./datasets/nyuv2 --save_epoch_freq 5 --loadSize 640 --instance_feat --netG global`

And the error:

`/pytorch/aten/src/THC/THCTensorScatterGather.cu:188: void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = -1]: block: [22,0,0], thread: [127,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorScatterGather.cu line=380 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 71, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/juancevedo/pix2pixHD/models/pix2pixHD_model.py", line 158, in forward
    input_label, inst_map, real_image, feat_map = self.encode_input(label, inst, image, feat)
  File "/home/juancevedo/pix2pixHD/models/pix2pixHD_model.py", line 122, in encode_input
    input_label = input_label.scatter_(1, label_map.data.long().cuda(), 1.0)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:380`

Here are two sample images:

Label image:
![9](https://user-images.githubusercontent.com/6580675/86295078-ab3da600-bbaa-11ea-94f6-26dc2d1e9a89.png)

Train image:

![9](https://user-images.githubusercontent.com/6580675/86295132-c7414780-bbaa-11ea-9428-dc3175a1cfec.png)

I suspect something changed with new pytorch but I don't know how to make the fix.

Any help is appreciated. Thank you.

**Comment by yliats** [comment]
"I trained a model using rgb values and the train folders train_A and train_B without any issues."

Could you please elaborate on what kind of images you had in train_A and train_B? What base_options and train_options did you use?

Thanks.

**Comment by entrpn** [comment]
train_A holds images that will be passed to the generator and train_B are the source of truth images. For example:

train_A/1.jpg

train_B/1.pg

and the command i used:

```nohup python train.py --label_nc 0 --no_instance --name w --dataroot ./datasets/w --save_epoch_freq 5 --loadSize 512 &```

Hope that helps.

**Comment by yliats** [comment]
train_B/1.jpg is an RGB image? in my case its grayscale, so when I add `--output_nc 1` , I get a dimensional mismatch error.
Another problem is that it reads grayscale images as binary (0 for pixels that are 0, and 1 otherwise).

Thanks.
P.S. Sorry for using your post to talk about my issue.

**Comment by entrpn** [comment]
Hi yliats, I'm not sure because I didn't train with rgb to grayscale but --output_nc 1 should work. What dimensional mismatch are you getting?
