### ISSUE TITLE
Training Problem?

### ISSUE THREAD

**Issue by happsky** [NVIDIA/pix2pixHD#22]
(epoch: 13, iters: 1878, time: 3.216) G_GAN_Feat: 9.109 G_VGG: 7.598 G_GAN: 0.842 D_fake: 0.309 D_real: 0.296
(epoch: 13, iters: 1879, time: 3.255) G_GAN_Feat: 10.054 G_VGG: 8.721 G_GAN: 1.329 D_fake: 0.114 D_real: 0.057
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Exception socket.error: error(111, 'Connection refused') in <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7fc64fe3c190>> ignored
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    visualizer.display_current_results(visuals, epoch, total_steps)
  File "/data2/dx/th/pix2pixHD/util/visualizer.py", line 66, in display_current_results
    util.save_image(image_numpy, img_path)
  File "/data2/dx/th/pix2pixHD/util/util.py", line 39, in save_image
    image_pil.save(image_path)
  File "/home/dx/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 1893, in save   
    save_handler(self, fp, filename)
  File "/home/dx/anaconda2/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 739, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/home/dx/anaconda2/lib/python2.7/site-packages/PIL/ImageFile.py", line 496, in _save
    s = e.encode_to_file(fh, bufsize)
  File "/home/dx/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 16100) is killed by signal: Bus error.

**Comment by tcwang0509** [comment]
As the message complained it might be caused by insufficient shared memory. Could you share about your machine spec? Does this error constantly happen?

**Comment by shaibagon** [comment]
can [this](https://github.com/pytorch/pytorch/issues/2244) be related?
