### ISSUE TITLE
Assertion Error Train_A directory is not valid

### ISSUE THREAD

**Issue by georgezefko** [NVIDIA/pix2pixHD#235]
Hey 

I am trying to run the model in Google colab and I have images of size 256X256. 

When I run this command 
!python train.py --label_nc 0 --no_instance --name w --dataroot /content/drive/My\ Drive/pix2pixHD-colab/pix2pixHD/datasets/w --resize_or_crop 256 --continue_train --display_freq 100 --checkpoints_dir /content/drive/My\ Drive/pix2pixHD-colab/pix2pixHD/checkpoints --which_epoch latest --save_epoch_freq 10 

I get the following error:

Resuming from epoch 1 at iteration 0
CustomDatasetDataLoader
dataset [AlignedDataset] was created
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    data_loader = CreateDataLoader(opt)
  File "/content/drive/My Drive/pix2pixHD-colab/pix2pixHD/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/content/drive/My Drive/pix2pixHD-colab/pix2pixHD/data/custom_dataset_data_loader.py", line 20, in initialize
    self.dataset = CreateDataset(opt)
  File "/content/drive/My Drive/pix2pixHD-colab/pix2pixHD/data/custom_dataset_data_loader.py", line 11, in CreateDataset
    dataset.initialize(opt)
  File "/content/drive/My Drive/pix2pixHD-colab/pix2pixHD/data/aligned_dataset.py", line 14, in initialize
    self.A_paths = sorted(make_dataset(self.dir_A))
  File "/content/drive/My Drive/pix2pixHD-colab/pix2pixHD/data/image_folder.py", line 23, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: /content/drive/My Drive/pix2pixHD-colab/pix2pixHD/datasets/w/train_A is not a valid directory

it seems there is problem with the data but i am not sure what it is and how to solve it.

Thank you for your time!

**Comment by georgezefko** [comment]
It was silly error the w folder was in wrong directory

**Comment by Parth527** [comment]
Hey, can you elaborate your solution? 
Thank you:)
