### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by krummrey** [NVIDIA/pix2pixHD#243]
Pix2PixHD was running fine. Today it stoped working while trying to load the model.
Is there a different download location? How would I implement it?
```
Traceback (most recent call last):
  File "/pix2pixHD/models/base_model.py", line 62, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = create_model(opt)
  File "/pix2pixHD/models/models.py", line 13, in create_model
    model.initialize(opt)
  File "/pix2pixHD/models/pix2pixHD_model.py", line 58, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path)            
  File "/pix2pixHD/models/base_model.py", line 64, in load_network
    pretrained_dict = torch.load(save_path)                
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by krummrey** [comment]
Sorry, it was a broken latest save state.
