### ISSUE TITLE
Is it possible to convert image to image with instance maps?

### ISSUE THREAD

**Issue by matthewn4444** [NVIDIA/pix2pixHD#295]
Hello. I am trying the default example and modifying it to understand and I was wondering if I can run below command with instance maps going from image to image. I also changed _train_img_ to _train_B_ and _train_label_ to _train_A_

`python train.py --name label2city_512p --label_nc 0`

I get the issue where it tries to normalize the data with tensor type int32 instead of float32 so normalize fails. The std matrix was passed with 0.5 but if the tensor input is not a float it will convert to 0 and then the error trying to convert by 0 occurs.

```
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    for i, data in enumerate(dataset, start=epoch_iter):
  File "/home/me/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/me/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/me/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/me/.local/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/me/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/me/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/me/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/c/Programming/repositories/test/pix2pix/pix2pixHD/data/aligned_dataset.py", line 59, in __getitem__
    inst_tensor = transform_A(inst)
  File "/home/me/.local/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/me/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/me/.local/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 221, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/me/.local/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 336, in normalize
    raise ValueError('std evaluated to zero after conversion to {}, leading to division by zero.'.format(dtype))
ValueError: std evaluated to zero after conversion to torch.int32, leading to division by zero.
```

If I ignore instance maps, then it will run fine. Is it possible to train image to image with instance maps?

**Comment by AmitAilianiSDC** [comment]
I was wondering if you were able to do rgb2rgb with instance maps?
