### ISSUE TITLE
Schema not found exporting to onnx 

### ISSUE THREAD

**Issue by flamz3d** [NVIDIA/pix2pixHD#93]
Hello, I successfully trained a model on my own dataset, and the results are impressive.
I'd like now to export the model to onnx, but I'm running into anthis error during the export:

```
RuntimeError:
Schema not found for node: File a bug report.
Node: %input.65 : Float(1, 35, 1024, 2048) = aten::scatter(%97, %109, %108, %110), scope: InferenceModel
Input types: Float(1, 35, 1024, 2048), int, Long(1, 1, 1024, 2048), float
```

is this caused by a mismatch version of pix2pix -> pytorch?
any insights greatly appreciated.

**Comment by kaitingwang** [comment]
Hi, I'm trying to export GNMT to onnx using nvcr.io/nvidia/pytorch:19.01-py3 and I'm getting the same error:

```
Traceback (most recent call last):
  File "train.py", line 460, in <module>
    passed = main()
  File "/opt/conda/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "train.py", line 414, in main
    train_loss, train_perf = trainer.optimize(train_loader)
  File "/workspace/examples/gnmt/seq2seq/train/trainer.py", line 268, in optimize
    self.preallocate(data_loader, training=True)
  File "/workspace/examples/gnmt/seq2seq/train/trainer.py", line 255, in preallocate
    self.iterate(src, tgt, update=False, training=training)
  File "/workspace/examples/gnmt/seq2seq/train/trainer.py", line 126, in iterate
    torch.onnx.export(self.model,list_inputs, "/tmp/gnmt.onnx")
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 281, in _export
    example_outputs, propagate)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 227, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    torch._C._jit_pass_constant_propagation(graph)
RuntimeError:
Schema not found for node. File a bug report.
Node: %463 : Half(128, 49, 50) = aten::masked_fill(%461, %460, %462), scope: GNMT/ResidualRecurrentDecoder[decoder]/RecurrentAttention[att_rnn]/BahdanauAttention[attn]
```

Before hitting this error, I had to do a few things including make class GNMT forward method take only one input as follows:
```
    #def forward(self, input_encoder, input_enc_len, input_decoder):
    def forward(self, inputs):
        input_encoder, input_enc_len, input_decoder = inputs
        context = self.encode(input_encoder, input_enc_len)
        context = (context, input_enc_len, None)
```

This is because torch.onnx.export expects that forward only takes one input.  

I had to also fix the _iter_filter method in : /opt/conda/lib/python3.6/site-packages/torch/autograd/function.py

so that when it enters the exception path, it simply returns.

After all these hurdles, I run into the schema not found problem.

**Comment by kaitingwang** [comment]
I got around this problem by commenting out torch._C._jit_pass_constant_propagation(graph) at line 132 of util.py  (for now)
