### ISSUE TITLE
Cuda out of memory when i turn the opt.netG to the 'local' option with other default options 

### ISSUE THREAD

**Issue by LonglongaaaGo** [NVIDIA/pix2pixHD#96]
Hello!  Help me! 
when i use this project for train , it's ok when i train the default citycapes data  with the 'global' option.But when I turn the  opt.netG to the 'local' option ,I can see the GPU memory from 2000+MB to 10000+MB than the Cuda turn out the "out of memory". like this:

--------------------
Traceback (most recent call last):
  File "/home/k/Longlongaaago/pix2pixHD-master/trainRoot/train.py", line 91, in <module>
    model.module.optimizer_G.step()
  File "/home/k/SoftWare/anaconda2/envs/python2/lib/python2.7/site-packages/torch/optim/adam.py", line 100, in step
    denom = exp_avg_sq.sqrt().add_(group['eps'])
RuntimeError: CUDA error: out of memory
--------------------
but I know , I had not change any code for this project . my train options  below:
 ------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
data_type: 32
dataroot: ../datasets/cityscapes/
debug: False
display_freq: 100
display_winsize: 512
feat_num: 3
fineSize: 512
gpu_ids: [0]
input_nc: 3
instance_feat: False
isTrain: True
label_feat: False
label_nc: 35
lambda_feat: 10.0
loadSize: 1024
load_features: False
load_pretrain: 
lr: 0.0002
max_dataset_size: inf
model: pix2pixHD
nThreads: 2
n_blocks_global: 9
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 4
n_layers_D: 3
n_local_enhancers: 1
name: label2city_512p
ndf: 64
nef: 16
netG: global
ngf: 64
niter: 100
niter_decay: 100
niter_fix_global: 0
no_flip: False
no_ganFeat_loss: False
no_html: False
no_instance: False
no_lsgan: False
no_vgg_loss: False
norm: instance
num_D: 2
output_nc: 3
phase: train
pool_size: 0
print_freq: 100
resize_or_crop: scale_width
save_epoch_freq: 10
save_latest_freq: 1000
serial_batches: False
tf_log: False
use_dropout: False
verbose: False
which_epoch: latest
-------------- End ----------------
by the way, my GPU card is TAITAN about 12GB memory!!
Help me ! thank you very much!!

**Comment by zhangdan8962** [comment]
Hi, can you share with me how to fix this problem or what did you find eventually?

**Comment by vishwas1234567** [comment]
just return to the cuda environment and clear the cached just give a try to clear all the power hogs if has encountered and also get the performance indicators right what your GDDR size or else share what is the version of the cuda and also the name of the card we can figure it out we will figure it out.if its fermi we can  have a look at it

**Comment by vishwas1234567** [comment]
even tesla architecture codes differs so we have to have a look at it and if you have developed the code.
